window.AULAS_1_DATA = {
  L1: [
    { it: 'abbandonare', pt: 'abandonar' },
    { it: 'accendere', pt: 'acender' },
    { it: 'addormentarsi', pt: 'adormecer' },
    { it: 'aiuto', pt: 'ajuda' },
    { it: 'agosto', pt: 'agosto' },
    { it: 'alba', pt: 'nascer do sol' },
    { it: 'alcuni', pt: 'alguns' },
    { it: 'amare', pt: 'amar' },
    { it: 'ancora', pt: 'ainda' },
    { it: 'ancora di più', pt: 'ainda mais' },
    { it: 'anno scorso', pt: 'ano passado' },
    { it: 'antipatico', pt: 'antipático' },
    { it: 'aspettare', pt: 'esperar' },
    { it: 'apprezzare', pt: 'apreciar' },
    { it: 'aprire', pt: 'abrir' },
    { it: 'aquilone', pt: 'pipa' },
    { it: 'armadio', pt: 'armário' },
    { it: 'ascoltare', pt: 'escutar' },
    { it: 'aspettare di', pt: 'esperar para' },
    { it: 'assaggiare', pt: 'experimentar um sabor' },
    { it: 'aula', pt: 'sala de aula' },
    { it: 'autunno', pt: 'outono' },
    { it: 'avere fame', pt: 'estar com fome' },
    { it: 'avere sete', pt: 'estar com sede' },
    { it: 'bar', pt: 'bar' },
    { it: 'barzelletta', pt: 'piada' },
    { it: 'bello', pt: 'bonito' },
    { it: 'bene', pt: 'bem' },
    { it: 'biblioteca', pt: 'biblioteca' },
    { it: 'bicicletta', pt: 'bicicleta' },
    { it: 'bollita', pt: 'conta' },
    { it: 'bottiglia', pt: 'garrafa' },
    { it: 'brutto', pt: 'feio' },
    { it: 'buono', pt: 'bom' },
    { it: 'buon viaggio', pt: 'boa viagem' },
    { it: 'buttare giocare', pt: 'jogar' },
    { it: 'buttare via', pt: 'jogar fora' },
    { it: 'caffellatte', pt: 'café com leite' },
    { it: 'camminare', pt: 'caminhar / andar' },
    { it: 'canzone', pt: 'música' },
    { it: 'capire', pt: 'entender' },
    { it: 'cappone ave Italiana', pt: 'receita do Veneto' },
    { it: 'cappuccino', pt: 'cappuccino' },
    { it: 'cellulare', pt: 'celular' },
    { it: 'cena', pt: 'jantar (substantivo)' },
    { it: 'cenare', pt: 'jantar (verbo)' },
    { it: 'certo', pt: 'com certeza' },
    { it: 'cioccolata', pt: 'chocolate' },
    { it: 'ciao', pt: 'oi / tchau' },
    { it: 'chiave', pt: 'chave' },
    { it: 'chiedere', pt: 'perguntar / pedir' },
    { it: 'chiedere di', pt: 'pedir para' },
    { it: 'chi sa', pt: 'quem sabe' },
    { it: 'chiudere', pt: 'fechar' },
    { it: 'come', pt: 'como' },
    { it: 'classe', pt: 'turma' },
    { it: 'colazione', pt: 'café da manhã' },
    { it: 'colore', pt: 'cor' },
    { it: 'cominciare a lavorare', pt: 'começar a trabalhar' },
    { it: 'cosa di?', pt: 'o que você acha?' },
    { it: 'di lingua italiana', pt: 'da língua italiana' },
    { it: 'cravatta', pt: 'gravata' },
    { it: 'cuocere', pt: 'cozinhar' },
    { it: 'cugino', pt: 'primo' }
  ],
  L2: [
    { it: 'da allora', pt: 'desde então' },
    { it: 'da bere', pt: 'para beber' },
    { it: 'da mangiare', pt: 'para comer' },
    { it: 'da solo', pt: 'sozinho' },
    { it: 'da un anno', pt: 'há um ano' },
    { it: 'di più', pt: 'mais' },
    { it: 'di solito', pt: 'de costume' },
    { it: 'dell\'anno', pt: 'do ano' },
    { it: 'depurare', pt: 'desintoxicar' },
    { it: 'dicembre', pt: 'dezembro' },
    { it: 'diciannove', pt: 'dezenove' },
    { it: 'dimenticarsi', pt: 'esquecer' },
    { it: 'e-mail', pt: 'e-mail' },
    { it: 'edificio', pt: 'prédio' },
    { it: 'essa', pt: 'ela' },
    { it: 'estate', pt: 'verão' },
    { it: 'faraona', pt: 'galinha d\'Angola' },
    { it: 'fare', pt: 'fazer' },
    { it: 'fare colazione', pt: 'tomar café da manhã' },
    { it: 'febbraio', pt: 'fevereiro' },
    { it: 'festivo', pt: 'feriado' },
    { it: 'finestra', pt: 'janela' },
    { it: 'finire', pt: 'terminar' },
    { it: 'finire di studiare', pt: 'terminar de estudar' },
    { it: 'fino', pt: 'até' },
    { it: 'fiume', pt: 'rio' },
    { it: 'forno', pt: 'forno' },
    { it: 'fuochi d\'artificio', pt: 'fogos de artifício' },
    { it: 'gelateria', pt: 'sorveteria' },
    { it: 'gelato', pt: 'sorvete' },
    { it: 'gennaio', pt: 'janeiro' },
    { it: 'giornata', pt: 'dia' },
    { it: 'giugno', pt: 'junho' },
    { it: 'gomma', pt: 'borracha' },
    { it: 'grasso', pt: 'gordo' },
    { it: 'grosso', pt: 'grande' },
    { it: 'guardare', pt: 'olhar / assistir' },
    { it: 'i miei', pt: 'meus pais' },
    { it: 'imparare', pt: 'aprender' },
    { it: 'in corso', pt: 'em presente' },
    { it: 'in Italia', pt: 'na Itália toda' },
    { it: 'invece', pt: 'em vez de' },
    { it: 'influenza', pt: 'gripe' },
    { it: 'informazione', pt: 'informação' },
    { it: 'in torno', pt: 'volta' },
    { it: 'invito', pt: 'convite' }
  ],
  L3: [
    { it: 'lago', pt: 'lago' },
    { it: 'lasciare', pt: 'deixar' },
    { it: 'lato', pt: 'lado' },
    { it: 'lavare', pt: 'lavar' },
    { it: 'lasagna', pt: 'lasanha' },
    { it: 'lenticchia', pt: 'lentilha' },
    { it: 'leone', pt: 'leão' },
    { it: 'lingua', pt: 'idioma / língua' },
    { it: 'luce', pt: 'luz' },
    { it: 'luglio', pt: 'julho' },
    { it: 'luogo', pt: 'lugar' },
    { it: 'madre', pt: 'mãe' },
    { it: 'maestro', pt: 'professor de ensino fundamental' },
    { it: 'male', pt: 'mal' },
    { it: 'magro', pt: 'magro' },
    { it: 'mai', pt: 'nunca' },
    { it: 'manufatto', pt: 'trabalho manual' },
    { it: 'mare', pt: 'mar' },
    { it: 'marmellata', pt: 'geleia' },
    { it: 'marzo', pt: 'março' },
    { it: 'matta', pt: 'maluco / louco' },
    { it: 'matrigna', pt: 'madrasta' },
    { it: 'meno', pt: 'menos' },
    { it: 'meno di...', pt: 'menos que...' },
    { it: 'merenda', pt: 'café da tarde' },
    { it: 'mezzanotte', pt: 'meia-noite' },
    { it: 'mezzo di trasporto', pt: 'meio de transporte' },
    { it: 'mezzogiorno', pt: 'meio-dia' },
    { it: 'mica', pt: 'não (enfático)' },
    { it: 'minuto', pt: 'minuto' },
    { it: 'montagna', pt: 'montanha' },
    { it: 'museo', pt: 'museu' },
    { it: 'neve', pt: 'neve' },
    { it: 'non lo so', pt: 'não sei' },
    { it: 'notte', pt: 'noite' },
    { it: 'novembre', pt: 'novembro' },
    { it: 'nuovo', pt: 'novo' },
    { it: 'odore', pt: 'cheiro' },
    { it: 'oggi', pt: 'hoje' },
    { it: 'ogni', pt: 'cada' },
    { it: 'ottobre', pt: 'outubro' }
  ],
  L4: [
    { it: 'pace', pt: 'paz' },
    { it: 'paesaggio', pt: 'paisagem' },
    { it: 'paese', pt: 'país' },
    { it: 'pagare', pt: 'pagar' },
    { it: 'pagina', pt: 'página' },
    { it: 'palla', pt: 'bola' },
    { it: 'panificio', pt: 'padaria' },
    { it: 'parente', pt: 'parente' },
    { it: 'penna', pt: 'caneta' },
    { it: 'pensare', pt: 'pensar' },
    { it: 'pensare di', pt: 'pensar sobre' },
    { it: 'per', pt: 'para / por' },
    { it: 'per lavoro', pt: 'para o trabalho' },
    { it: 'per niente', pt: 'nem um pouco' },
    { it: 'per piacere', pt: 'por favor' },
    { it: 'perdere', pt: 'perder' },
    { it: 'periferia', pt: 'periferia' },
    { it: 'periodo', pt: 'período' },
    { it: 'pesca', pt: 'pêssego' },
    { it: 'più', pt: 'mais' },
    { it: 'più di...', pt: 'mais que...' },
    { it: 'pizza', pt: 'pizza' },
    { it: 'pomeriggio', pt: 'tarde' },
    { it: 'porta', pt: 'porta' },
    { it: 'portafogli', pt: 'carteira' },
    { it: 'portare', pt: 'levar / trazer' },
    { it: 'potere', pt: 'poder' },
    { it: 'pranzare', pt: 'almoçar' },
    { it: 'pranzo', pt: 'almoço' },
    { it: 'prendere', pt: 'pegar / tomar' },
    { it: 'primo', pt: 'primeiro' },
    { it: 'professore', pt: 'professor de ensino médio e superior' },
    { it: 'profumo', pt: 'perfume' },
    { it: 'prolungare', pt: 'prolongar' },
    { it: 'provare', pt: 'tentar' },
    { it: 'provincia', pt: 'província' },
    { it: 'qualche volta', pt: 'às vezes' },
    { it: 'qualità', pt: 'qualidade' },
    { it: 'quartiere', pt: 'bairro' },
    { it: 'quello', pt: 'aquele / aquilo' },
    { it: 'quindi', pt: 'então' }
  ],
  L5: [
    { it: 'rappresentare', pt: 'representar' },
    { it: 'regalare', pt: 'presentear' },
    { it: 'regione', pt: 'região' },
    { it: 'ridere', pt: 'rir' },
    { it: 'rilassarsi', pt: 'relaxar' },
    { it: 'rimanere', pt: 'ficar' },
    { it: 'riparare', pt: 'consertar' },
    { it: 'riposo', pt: 'descanso' },
    { it: 'ristorante', pt: 'restaurante' },
    { it: 'ritrovare', pt: 'reencontrar' },
    { it: 'riuscire', pt: 'conseguir' },
    { it: 'rotondo', pt: 'redondo' },
    { it: 'rumoroso', pt: 'barulhento' },
    { it: 'salire', pt: 'subir' },
    { it: 'salutare', pt: 'cumprimentar' },
    { it: 'sapere', pt: 'saber' },
    { it: 'ho saputo che', pt: 'soube que' },
    { it: 'scambiare', pt: 'trocar' },
    { it: 'scambio', pt: 'troca' },
    { it: 'scegliere', pt: 'escolher' },
    { it: 'scendere', pt: 'descer' },
    { it: 'scuola', pt: 'escola' },
    { it: 'scorso', pt: 'passado' },
    { it: 'scopa', pt: 'vassoura' },
    { it: 'secondo te?', pt: 'na sua opinião?' },
    { it: 'sentire', pt: 'sentir / ouvir' },
    { it: 'sentirei', pt: 'sentirei' },
    { it: 'sentirei i parenti', pt: 'falar com os parentes' },
    { it: 'sentire al telefono', pt: 'falar ao telefone' },
    { it: 'sentire parlare', pt: 'ouvir falar' },
    { it: 'settembre', pt: 'setembro' },
    { it: 'signore', pt: 'senhor' },
    { it: 'silenzioso', pt: 'silencioso' },
    { it: 'simpatico', pt: 'simpático' },
    { it: 'solo', pt: 'sozinho / somente' },
    { it: 'sorridente', pt: 'sorridente' },
    { it: 'spazzatura', pt: 'lixo' },
    { it: 'spegnere', pt: 'desligar / apagar' },
    { it: 'spettacolo', pt: 'show / espetáculo' },
    { it: 'spiaggia', pt: 'praia' },
    { it: 'sprinto', pt: 'lanche' },
    { it: 'stagione', pt: 'estação' },
    { it: 'stanco', pt: 'cansado' },
    { it: 'stare bene', pt: 'estar bem' },
    { it: 'stare male', pt: 'estar mal / passar mal' },
    { it: 'svegliarsi', pt: 'acordar' }
  ],
  L6: [
    { it: 'tanto', pt: 'tanto' },
    { it: 'tanto... quanto...', pt: 'tanto... quanto...' },
    { it: 'tassa', pt: 'imposto' },
    { it: 'telefono', pt: 'telefone' },
    { it: 'televisione', pt: 'televisão' },
    { it: 'temperino', pt: 'apontador' },
    { it: 'toast', pt: 'torrada' },
    { it: 'tornare', pt: 'voltar' },
    { it: 'torta', pt: 'bolo' },
    { it: 'tramezzino', pt: 'tipo de sanduíche' },
    { it: 'tramonto', pt: 'pôr do sol' },
    { it: 'trasporto', pt: 'transporte' },
    { it: 'trattoria', pt: 'trattoria' }
  ]
};
