window.LEVELS_DATA = {
  L1: [
    { it: 'ciao', pt: 'oi' },
    { it: 'sì', pt: 'sim' },
    { it: 'no', pt: 'não' },
    { it: 'grazie', pt: 'obrigado' },
    { it: 'prego', pt: 'de nada' },
    { it: 'buongiorno', pt: 'bom dia' },
    { it: 'buonasera', pt: 'boa noite' },
    { it: 'arrivederci', pt: 'até logo' },
    { it: 'come', pt: 'como' },
    { it: 'dove', pt: 'onde' },
    { it: 'perché', pt: 'porquê' },
    { it: 'quando', pt: 'quando' },
    { it: 'casa', pt: 'moradia' },
    { it: 'madre', pt: 'mãe' },
    { it: 'padre', pt: 'pai' },
    { it: 'figlio', pt: 'filho' },
    { it: 'sorella', pt: 'irmã' },
    { it: 'fratello', pt: 'irmão' },
    { it: 'amico', pt: 'amigo' },
    { it: 'acqua', pt: 'água' },
    { it: 'caffè', pt: 'café' },
    { it: 'pane', pt: 'pão' },
    { it: 'vino', pt: 'vinho' },
    { it: 'carne', pt: 'carne' },
    { it: 'pesce', pt: 'peixe' },
    { it: 'frutta', pt: 'fruta' },
    { it: 'latte', pt: 'leite' },
    { it: 'olio', pt: 'azeite' },
    { it: 'sale', pt: 'sal' },
    { it: 'zucchero', pt: 'açúcar' },
    { it: 'formaggio', pt: 'queijo' },
    { it: 'uovo', pt: 'ovo' },
    { it: 'pasta', pt: 'macarrão' },
    { it: 'pomodoro', pt: 'tomate' },
    { it: 'bicchiere', pt: 'copo' },
    { it: 'piatto', pt: 'prato' },
    { it: 'coltello', pt: 'faca' },
    { it: 'forchetta', pt: 'garfo' },
    { it: 'cucchiaio', pt: 'colher' },
    { it: 'tavolo', pt: 'mesa' },
    { it: 'sedia', pt: 'cadeira' },
    { it: 'letto', pt: 'cama' },
    { it: 'porta', pt: 'porta' },
    { it: 'finestra', pt: 'janela' },
    { it: 'strada', pt: 'rua' },
    { it: 'città', pt: 'cidade' },
    { it: 'piazza', pt: 'praça' },
    { it: 'parco', pt: 'parque' },
    { it: 'scuola', pt: 'escola' },
    { it: 'ospedale', pt: 'hospital' },
    { it: 'albergo', pt: 'hotel' },
    { it: 'ristorante', pt: 'restaurante' },
    { it: 'supermercato', pt: 'supermercado' },
    { it: 'macchina', pt: 'carro' },
    { it: 'autobus', pt: 'ônibus' },
    { it: 'treno', pt: 'trem' },
    { it: 'aereo', pt: 'avião' },
    { it: 'nome', pt: 'nome' },
    { it: 'cognome', pt: 'sobrenome' },
    { it: 'Italia', pt: 'Itália' },
    { it: 'Roma', pt: 'Roma' }
  ],
  L2: [
    { it: 'abitare', pt: 'morar' },
    { it: 'andare', pt: 'ir' },
    { it: 'avere', pt: 'ter' },
    { it: 'essere', pt: 'ser' },
    { it: 'fare', pt: 'fazer' },
    { it: 'stare', pt: 'ficar' },
    { it: 'parlare', pt: 'falar' },
    { it: 'mangiare', pt: 'comer' },
    { it: 'bere', pt: 'beber' },
    { it: 'dormire', pt: 'dormir' },
    { it: 'leggere', pt: 'ler' },
    { it: 'scrivere', pt: 'escrever' },
    { it: 'capire', pt: 'entender' },
    { it: 'vedere', pt: 'ver' },
    { it: 'sentire', pt: 'ouvir' },
    { it: 'uscire', pt: 'sair' },
    { it: 'entrare', pt: 'entrar' },
    { it: 'comprare', pt: 'comprar' },
    { it: 'vendere', pt: 'vender' },
    { it: 'lavorare', pt: 'trabalhar' },
    { it: 'studiare', pt: 'estudar' },
    { it: 'giocare', pt: 'jogar' },
    { it: 'cantare', pt: 'cantar' },
    { it: 'ballare', pt: 'dançar' },
    { it: 'viaggiare', pt: 'viajar' },
    { it: 'visitare', pt: 'visitar' },
    { it: 'aiutare', pt: 'ajudar' },
    { it: 'chiamare', pt: 'chamar' },
    { it: 'pensare', pt: 'pensar' },
    { it: 'sapere', pt: 'saber' },
    { it: 'volere', pt: 'querer' },
    { it: 'potere', pt: 'poder' },
    { it: 'dovere', pt: 'dever' },
    { it: 'piacere', pt: 'agradar' },
    { it: 'conoscere', pt: 'conhecer' },
    { it: 'amare', pt: 'amar' },
    { it: 'odiare', pt: 'odiar' }
  ],
  L3: [
    { it: 'giorno', pt: 'dia' },
    { it: 'settimana', pt: 'semana' },
    { it: 'mese', pt: 'mês' },
    { it: 'anno', pt: 'ano' },
    { it: 'lunedì', pt: 'segunda-feira' },
    { it: 'martedì', pt: 'terça-feira' },
    { it: 'mercoledì', pt: 'quarta-feira' },
    { it: 'giovedì', pt: 'quinta-feira' },
    { it: 'venerdì', pt: 'sexta-feira' },
    { it: 'sabato', pt: 'sábado' },
    { it: 'domenica', pt: 'domingo' },
    { it: 'gennaio', pt: 'janeiro' },
    { it: 'febbraio', pt: 'fevereiro' },
    { it: 'marzo', pt: 'março' },
    { it: 'aprile', pt: 'abril' },
    { it: 'maggio', pt: 'maio' },
    { it: 'giugno', pt: 'junho' },
    { it: 'luglio', pt: 'julho' },
    { it: 'agosto', pt: 'agosto' },
    { it: 'settembre', pt: 'setembro' },
    { it: 'ottobre', pt: 'outubro' },
    { it: 'novembre', pt: 'novembro' },
    { it: 'dicembre', pt: 'dezembro' },
    { it: 'primavera', pt: 'primavera' },
    { it: 'estate', pt: 'verão' },
    { it: 'autunno', pt: 'outono' },
    { it: 'inverno', pt: 'inverno' },
    { it: 'caldo', pt: 'calor' },
    { it: 'freddo', pt: 'frio' },
    { it: 'bello', pt: 'bonito' },
    { it: 'brutto', pt: 'feio' },
    { it: 'grande', pt: 'grande' },
    { it: 'piccolo', pt: 'pequeno' },
    { it: 'alto', pt: 'alto' },
    { it: 'basso', pt: 'baixo' },
    { it: 'buono', pt: 'bom' },
    { it: 'cattivo', pt: 'mau' },
    { it: 'nuovo', pt: 'novo' },
    { it: 'vecchio', pt: 'velho' },
    { it: 'giovane', pt: 'jovem' }
  ],
  L4: [
    { it: 'macchina', pt: 'carro (como objeto)' },
    { it: 'carta', pt: 'papel' },
    { it: 'giornale', pt: 'jornal' },
    { it: 'rivista', pt: 'revista' },
    { it: 'libro', pt: 'livro' },
    { it: 'quaderno', pt: 'caderno' },
    { it: 'penna', pt: 'caneta' },
    { it: 'matita', pt: 'lápis' },
    { it: 'zaino', pt: 'mochila' },
    { it: 'orologio', pt: 'relógio' },
    { it: 'occhiali', pt: 'óculos' },
    { it: 'telefono', pt: 'telefone' },
    { it: 'computer', pt: 'computador' },
    { it: 'internet', pt: 'internet' },
    { it: 'radio', pt: 'rádio' },
    { it: 'televisione', pt: 'televisão' },
    { it: 'film', pt: 'filme' },
    { it: 'musica', pt: 'música' },
    { it: 'arte', pt: 'arte' },
    { it: 'storia', pt: 'história' },
    { it: 'geografia', pt: 'geografia' },
    { it: 'matematica', pt: 'matemática' },
    { it: 'scienza', pt: 'ciência' },
    { it: 'diritto', pt: 'direito' },
    { it: 'economia', pt: 'economia' },
    { it: 'politica', pt: 'política' },
    { it: 'religione', pt: 'religião' },
    { it: 'psicologia', pt: 'psicologia' },
    { it: 'filosofia', pt: 'filosofia' },
    { it: 'letteratura', pt: 'literatura' },
    { it: 'poesia', pt: 'poesia' },
    { it: 'romanzo', pt: 'romance' },
    { it: 'racconto', pt: 'conto' },
    { it: 'dialogo', pt: 'diálogo' },
    { it: 'conversazione', pt: 'conversação' },
    { it: 'tradizione', pt: 'tradição' },
    { it: 'cultura', pt: 'cultura' },
    { it: 'lingua', pt: 'língua' },
    { it: 'italiano', pt: 'italiano' },
    { it: 'inglese', pt: 'inglês' },
    { it: 'francese', pt: 'francês' },
    { it: 'spagnolo', pt: 'espanhol' },
    { it: 'tedesco', pt: 'alemão' },
    { it: 'portoghese', pt: 'português' }
  ],
  L5: [
    { it: 'uguale', pt: 'igual' },
    { it: 'diverso', pt: 'diferente' },
    { it: 'anche', pt: 'também' },
    { it: 'invece', pt: 'em vez disso' },
    { it: 'mentre', pt: 'enquanto' },
    { it: 'durante', pt: 'durante' },
    { it: 'dopo', pt: 'depois' },
    { it: 'prima', pt: 'antes' },
    { it: 'ultimo', pt: 'último' },
    { it: 'prossimo', pt: 'próximo' },
    { it: 'ogni', pt: 'cada' },
    { it: 'tanto', pt: 'tanto' },
    { it: 'poco', pt: 'pouco' },
    { it: 'molto', pt: 'muito' },
    { it: 'sempre', pt: 'sempre' },
    { it: 'mai', pt: 'nunca' },
    { it: 'già', pt: 'já' },
    { it: 'ancora', pt: 'ainda' },
    { it: 'appena', pt: 'apenas' },
    { it: 'proprio', pt: 'mesmo' },
    { it: 'sicuro', pt: 'seguro' },
    { it: 'forse', pt: 'talvez' },
    { it: 'magari', pt: 'quem dera' },
    { it: 'principalmente', pt: 'principalmente' },
    { it: 'frequentemente', pt: 'frequentemente' },
    { it: 'normalmente', pt: 'normalmente' },
    { it: 'necessariamente', pt: 'necessariamente' },
    { it: 'probabilmente', pt: 'provavelmente' },
    { it: 'particolarmente', pt: 'particularmente' },
    { it: 'generalmente', pt: 'geralmente' },
    { it: 'completamente', pt: 'completamente' },
    { it: 'assolutamente', pt: 'absolutamente' },
    { it: 'fortunatamente', pt: 'felizmente' },
    { it: 'sfortunatamente', pt: 'infelizmente' },
    { it: 'finalmente', pt: 'finalmente' },
    { it: 'recentemente', pt: 'recentemente' },
    { it: 'perfettamente', pt: 'perfeitamente' },
    { it: 'esattamente', pt: 'exatamente' },
    { it: 'semplicemente', pt: 'simplesmente' },
    { it: 'certamente', pt: 'certamente' },
    { it: 'attualmente', pt: 'atualmente' }
  ],
  L6: [
    { it: 'quindi', pt: 'portanto' },
    { it: 'perciò', pt: 'por isso' },
    { it: 'poiché', pt: 'pois' },
    { it: 'qualora', pt: 'caso' },
    { it: 'affinché', pt: 'para que' },
    { it: 'sebbene', pt: 'embora' },
    { it: 'malgrado', pt: 'apesar de' },
    { it: 'nonostante', pt: 'não obstante' },
    { it: 'simultaneamente', pt: 'simultaneamente' },
    { it: 'contemporaneamente', pt: 'contemporaneamente' },
    { it: 'conseguentemente', pt: 'consequentemente' },
    { it: 'reciprocamente', pt: 'reciprocamente' },
    { it: 'specificamente', pt: 'especificamente' },
    { it: 'particolarmente', pt: 'particularmente' },
    { it: 'fondamentalmente', pt: 'fundamentalmente' },
    { it: 'sostanzialmente', pt: 'substancialmente' },
    { it: 'preliminarmente', pt: 'preliminarmente' },
    { it: 'successivamente', pt: 'sucessivamente' },
    { it: 'anteriormente', pt: 'anteriormente' },
    { it: 'posteriormente', pt: 'posteriormente' },
    { it: 'ulteriormente', pt: 'ulteriormente' },
    { it: 'contestualmente', pt: 'contextualmente' },
    { it: 'coerente', pt: 'coerente' },
    { it: 'evidente', pt: 'evidente' },
    { it: 'ovvio', pt: 'óbvio' },
    { it: 'plausibile', pt: 'plausível' },
    { it: 'verosimilmente', pt: 'verossimilmente' },
    { it: 'effettivamente', pt: 'efetivamente' },
    { it: 'difatti', pt: 'de fato' },
    { it: 'nondimeno', pt: 'não obstante' },
    { it: 'ciononostante', pt: 'não obstante' },
    { it: 'tuttavia', pt: 'todavia' },
    { it: 'eppure', pt: 'e no entanto' },
    { it: 'bensì', pt: 'mas sim' },
    { it: 'piuttosto', pt: 'antes' },
    { it: 'anziché', pt: 'ao invés de' },
    { it: 'oltre', pt: 'além de' },
    { it: 'inoltre', pt: 'além disso' }
  ]
};
